// 自动生成：Pokopia 真实方块目录（名称来源 Game8，图片来源 Serebii）
// 图片 assets/blocks/<id>.png (160x160)  cat: wall / floor / print / ground
export const CAT_LABEL = {"wall": "墙壁", "floor": "地板", "print": "花纹", "ground": "地形"};
export const BLOCK_TYPES = [
  {"id": "woodenwall", "en": "Wooden wall", "cn": "木墙", "cat": "wall", "color": "#7d5a2f", "img": "assets/blocks/woodenwall.png"},
  {"id": "lightwoodenwall", "en": "Light wooden wall", "cn": "浅色木墙", "cat": "wall", "color": "#d3ae60", "img": "assets/blocks/lightwoodenwall.png"},
  {"id": "paintedwall", "en": "Painted wall", "cn": "涂装墙", "cat": "wall", "color": "#d2c4bb", "img": "assets/blocks/paintedwall.png"},
  {"id": "plasterwall", "en": "Plaster wall", "cn": "灰泥墙", "cat": "wall", "color": "#cac8b6", "img": "assets/blocks/plasterwall.png"},
  {"id": "clothwall", "en": "Cloth wall", "cn": "布墙", "cat": "wall", "color": "#d0ccc9", "img": "assets/blocks/clothwall.png"},
  {"id": "guest_roomwall", "en": "Guest-room wall", "cn": "客舱墙", "cat": "wall", "color": "#cbcbc9", "img": "assets/blocks/guest_roomwall.png"},
  {"id": "starry_skywall", "en": "Starry-sky wall", "cn": "星空空墙", "cat": "wall", "color": "#383e77", "img": "assets/blocks/starry_skywall.png"},
  {"id": "cushywall", "en": "Cushy wall", "cn": "软包墙", "cat": "wall", "color": "#b43d4f", "img": "assets/blocks/cushywall.png"},
  {"id": "modernwall", "en": "Modern wall", "cn": "现代墙", "cat": "wall", "color": "#d3b08a", "img": "assets/blocks/modernwall.png"},
  {"id": "broken_tilingwall", "en": "Broken-tiling wall", "cn": "碎瓷砖墙", "cat": "wall", "color": "#cc9b9c", "img": "assets/blocks/broken_tilingwall.png"},
  {"id": "cobblestonewall", "en": "Cobblestone wall", "cn": "鹅卵石墙", "cat": "wall", "color": "#8b8c92", "img": "assets/blocks/cobblestonewall.png"},
  {"id": "brickwall", "en": "Brick wall", "cn": "砖墙", "cat": "wall", "color": "#bb6c49", "img": "assets/blocks/brickwall.png"},
  {"id": "stonebrickwall", "en": "Stone brick wall", "cn": "石砖墙", "cat": "wall", "color": "#a39a96", "img": "assets/blocks/stonebrickwall.png"},
  {"id": "aged_stonewall", "en": "Aged-stone wall", "cn": "旧石墙", "cat": "wall", "color": "#8f9c90", "img": "assets/blocks/aged_stonewall.png"},
  {"id": "patternedaged_stonewall", "en": "Patterned aged-stone wall", "cn": "旧石墙", "cat": "wall", "color": "#afb4a7", "img": "assets/blocks/patternedaged_stonewall.png"},
  {"id": "concretewall", "en": "Concrete wall", "cn": "混凝土墙", "cat": "wall", "color": "#afaaa7", "img": "assets/blocks/concretewall.png"},
  {"id": "roughwall", "en": "Rough wall", "cn": "粗面墙", "cat": "wall", "color": "#c9b98a", "img": "assets/blocks/roughwall.png"},
  {"id": "stripedwall", "en": "Striped wall", "cn": "条纹墙", "cat": "wall", "color": "#525f92", "img": "assets/blocks/stripedwall.png"},
  {"id": "bronzewall", "en": "Bronze wall", "cn": "青铜墙", "cat": "wall", "color": "#8f683d", "img": "assets/blocks/bronzewall.png"},
  {"id": "stylishbronzewall", "en": "Stylish bronze wall", "cn": "精致青铜墙", "cat": "wall", "color": "#917052", "img": "assets/blocks/stylishbronzewall.png"},
  {"id": "ironwall", "en": "Iron wall", "cn": "铁墙", "cat": "wall", "color": "#6f6f74", "img": "assets/blocks/ironwall.png"},
  {"id": "stylishironwall", "en": "Stylish iron wall", "cn": "精致铁墙", "cat": "wall", "color": "#777476", "img": "assets/blocks/stylishironwall.png"},
  {"id": "goldwall", "en": "Gold wall", "cn": "金墙", "cat": "wall", "color": "#a18942", "img": "assets/blocks/goldwall.png"},
  {"id": "stylishgoldwall", "en": "Stylish gold wall", "cn": "精致金墙", "cat": "wall", "color": "#a18b4c", "img": "assets/blocks/stylishgoldwall.png"},
  {"id": "crystalwall", "en": "Crystal wall", "cn": "水晶墙", "cat": "wall", "color": "#56ceea", "img": "assets/blocks/crystalwall.png"},
  {"id": "pokeballwall", "en": "Poke Ball wall", "cn": "精灵球墙", "cat": "wall", "color": "#d6d0ca", "img": "assets/blocks/pokeballwall.png"},
  {"id": "warningwall", "en": "Warning wall", "cn": "警示墙", "cat": "wall", "color": "#998f5d", "img": "assets/blocks/warningwall.png"},
  {"id": "stylishwall_upper", "en": "Stylish wall (upper)", "cn": "精致墙上", "cat": "wall", "color": "#9c8471", "img": "assets/blocks/stylishwall_upper.png"},
  {"id": "stylishwall_middle", "en": "Stylish wall (middle)", "cn": "精致墙中", "cat": "wall", "color": "#aea08f", "img": "assets/blocks/stylishwall_middle.png"},
  {"id": "stylishwall_lower", "en": "Stylish wall (lower)", "cn": "精致墙下", "cat": "wall", "color": "#9c8371", "img": "assets/blocks/stylishwall_lower.png"},
  {"id": "antiquewall_upper", "en": "Antique wall (upper)", "cn": "古董墙上", "cat": "wall", "color": "#956635", "img": "assets/blocks/antiquewall_upper.png"},
  {"id": "antiquewall_middle", "en": "Antique wall (middle)", "cn": "古董墙中", "cat": "wall", "color": "#926439", "img": "assets/blocks/antiquewall_middle.png"},
  {"id": "antiquewall_lower", "en": "Antique wall (lower)", "cn": "古董墙下", "cat": "wall", "color": "#906334", "img": "assets/blocks/antiquewall_lower.png"},
  {"id": "lightantiquewall_upper", "en": "Light antique wall (upper)", "cn": "浅色古董墙上", "cat": "wall", "color": "#d3bea7", "img": "assets/blocks/lightantiquewall_upper.png"},
  {"id": "lightantiquewall_middle", "en": "Light antique wall (middle)", "cn": "浅色古董墙中", "cat": "wall", "color": "#cfba9f", "img": "assets/blocks/lightantiquewall_middle.png"},
  {"id": "lightantiquewall_lower", "en": "Light antique wall (lower)", "cn": "浅色古董墙下", "cat": "wall", "color": "#d0bcac", "img": "assets/blocks/lightantiquewall_lower.png"},
  {"id": "woodenpillar_upper", "en": "Wooden pillar (upper)", "cn": "木柱上", "cat": "wall", "color": "#6f513e", "img": "assets/blocks/woodenpillar_upper.png"},
  {"id": "woodenpillar_middle", "en": "Wooden pillar (middle)", "cn": "木柱中", "cat": "wall", "color": "#75543e", "img": "assets/blocks/woodenpillar_middle.png"},
  {"id": "woodenpillar_lower", "en": "Wooden pillar (lower)", "cn": "木柱下", "cat": "wall", "color": "#684633", "img": "assets/blocks/woodenpillar_lower.png"},
  {"id": "stylishbrickwall_upper", "en": "Stylish brick wall (upper)", "cn": "精致砖墙上", "cat": "wall", "color": "#c8a996", "img": "assets/blocks/stylishbrickwall_upper.png"},
  {"id": "stylishbrickwall_middle", "en": "Stylish brick wall (middle)", "cn": "精致砖墙中", "cat": "wall", "color": "#c49f8a", "img": "assets/blocks/stylishbrickwall_middle.png"},
  {"id": "stylishbrickwall_lower", "en": "Stylish brick wall (lower)", "cn": "精致砖墙下", "cat": "wall", "color": "#c6a895", "img": "assets/blocks/stylishbrickwall_lower.png"},
  {"id": "stonepillar_upper", "en": "Stone pillar (upper)", "cn": "石柱上", "cat": "wall", "color": "#c9bbac", "img": "assets/blocks/stonepillar_upper.png"},
  {"id": "stonepillar_middle", "en": "Stone pillar (middle)", "cn": "石柱中", "cat": "wall", "color": "#cbbcad", "img": "assets/blocks/stonepillar_middle.png"},
  {"id": "stonepillar_lower", "en": "Stone pillar (lower)", "cn": "石柱下", "cat": "wall", "color": "#cabaac", "img": "assets/blocks/stonepillar_lower.png"},
  {"id": "popartwall_upper", "en": "Pop art wall (upper)", "cn": "波普艺术墙上", "cat": "wall", "color": "#8f9f84", "img": "assets/blocks/popartwall_upper.png"},
  {"id": "popartwall_middle", "en": "Pop art wall (middle)", "cn": "波普艺术墙中", "cat": "wall", "color": "#d0c096", "img": "assets/blocks/popartwall_middle.png"},
  {"id": "popartwall_lower", "en": "Pop art wall (lower)", "cn": "波普艺术墙下", "cat": "wall", "color": "#b0a384", "img": "assets/blocks/popartwall_lower.png"},
  {"id": "confectionerywall_upper", "en": "Confectionery wall (upper)", "cn": "糖果墙上", "cat": "wall", "color": "#d29790", "img": "assets/blocks/confectionerywall_upper.png"},
  {"id": "confectionerywall_middle", "en": "Confectionery wall (middle)", "cn": "糖果墙中", "cat": "wall", "color": "#d1a294", "img": "assets/blocks/confectionerywall_middle.png"},
  {"id": "confectionerywall_lower", "en": "Confectionery wall (lower)", "cn": "糖果墙下", "cat": "wall", "color": "#91abbe", "img": "assets/blocks/confectionerywall_lower.png"},
  {"id": "pokemoncenterwall_trim", "en": "Pokemon Center wall (trim)", "cn": "宝可梦中心墙装饰条", "cat": "wall", "color": "#cb816c", "img": "assets/blocks/pokemoncenterwall_trim.png"},
  {"id": "pokemoncenterwall_upper", "en": "Pokemon Center wall (upper)", "cn": "宝可梦中心墙上", "cat": "wall", "color": "#e1cba8", "img": "assets/blocks/pokemoncenterwall_upper.png"},
  {"id": "pokemoncenterwall_middle", "en": "Pokemon Center wall (middle)", "cn": "宝可梦中心墙中", "cat": "wall", "color": "#e6bd7f", "img": "assets/blocks/pokemoncenterwall_middle.png"},
  {"id": "pokemoncenterwall_lower", "en": "Pokemon Center wall (lower)", "cn": "宝可梦中心墙下", "cat": "wall", "color": "#cd8955", "img": "assets/blocks/pokemoncenterwall_lower.png"},
  {"id": "woodenflooring", "en": "Wooden flooring", "cn": "木地板", "cat": "floor", "color": "#8f6d54", "img": "assets/blocks/woodenflooring.png"},
  {"id": "diagonalwoodenflooring", "en": "Diagonal wooden flooring", "cn": "斜纹木地板", "cat": "floor", "color": "#d5b280", "img": "assets/blocks/diagonalwoodenflooring.png"},
  {"id": "crisscrosswoodenflooring", "en": "Crisscross wooden flooring", "cn": "交叉木地板", "cat": "floor", "color": "#855640", "img": "assets/blocks/crisscrosswoodenflooring.png"},
  {"id": "hardwoodflooring", "en": "Hardwood flooring", "cn": "硬木地板", "cat": "floor", "color": "#c69754", "img": "assets/blocks/hardwoodflooring.png"},
  {"id": "moderncarpeting", "en": "Modern carpeting", "cn": "现代地毯", "cat": "floor", "color": "#8190bd", "img": "assets/blocks/moderncarpeting.png"},
  {"id": "wovencarpeting", "en": "Woven carpeting", "cn": "编织地毯", "cat": "floor", "color": "#84858f", "img": "assets/blocks/wovencarpeting.png"},
  {"id": "fluffyflooring", "en": "Fluffy flooring", "cn": "蓬松地板", "cat": "floor", "color": "#d2cbc7", "img": "assets/blocks/fluffyflooring.png"},
  {"id": "softcarpeting", "en": "Soft carpeting", "cn": "柔软地毯", "cat": "floor", "color": "#20749a", "img": "assets/blocks/softcarpeting.png"},
  {"id": "extravagantcarpeting", "en": "Extravagant carpeting", "cn": "奢华地毯", "cat": "floor", "color": "#b64620", "img": "assets/blocks/extravagantcarpeting.png"},
  {"id": "tatamimat", "en": "Tatami mat", "cn": "榻榻米垫", "cat": "floor", "color": "#b2b06a", "img": "assets/blocks/tatamimat.png"},
  {"id": "feltmat", "en": "Felt mat", "cn": "毡垫", "cat": "floor", "color": "#c5b9b4", "img": "assets/blocks/feltmat.png"},
  {"id": "puffy_treepillar", "en": "Puffy-tree pillar", "cn": "蓬松柱", "cat": "wall", "color": "#8f6116", "img": "assets/blocks/puffy_treepillar.png"},
  {"id": "grassflooring", "en": "Grass flooring", "cn": "草地板", "cat": "floor", "color": "#6b9d46", "img": "assets/blocks/grassflooring.png"},
  {"id": "simpleflooring", "en": "Simple flooring", "cn": "简约地板", "cat": "floor", "color": "#d1cac7", "img": "assets/blocks/simpleflooring.png"},
  {"id": "marble", "en": "Marble", "cn": "大理石", "cat": "floor", "color": "#ccc0c2", "img": "assets/blocks/marble.png"},
  {"id": "stoneflooring", "en": "Stone flooring", "cn": "石地板", "cat": "floor", "color": "#b1b197", "img": "assets/blocks/stoneflooring.png"},
  {"id": "lined_stoneflooring", "en": "Lined-stone flooring", "cn": "条纹石地板", "cat": "floor", "color": "#b1b198", "img": "assets/blocks/lined_stoneflooring.png"},
  {"id": "darkmarbleflooring", "en": "Dark marble flooring", "cn": "深色大理石地板", "cat": "floor", "color": "#896b5a", "img": "assets/blocks/darkmarbleflooring.png"},
  {"id": "lightmarbleflooring", "en": "Light marble flooring", "cn": "浅色大理石地板", "cat": "floor", "color": "#9e8979", "img": "assets/blocks/lightmarbleflooring.png"},
  {"id": "aged_stoneflooring", "en": "Aged-stone flooring", "cn": "旧石地板", "cat": "floor", "color": "#90a192", "img": "assets/blocks/aged_stoneflooring.png"},
  {"id": "simplesquaretiling", "en": "Simple square tiling", "cn": "简约方块瓷砖", "cat": "floor", "color": "#cbc9c9", "img": "assets/blocks/simplesquaretiling.png"},
  {"id": "stylishtiling", "en": "Stylish tiling", "cn": "精致瓷砖", "cat": "floor", "color": "#9eb5b9", "img": "assets/blocks/stylishtiling.png"},
  {"id": "hexagonalflooring", "en": "Hexagonal flooring", "cn": "六边形地板", "cat": "floor", "color": "#aeaba7", "img": "assets/blocks/hexagonalflooring.png"},
  {"id": "shopflooring", "en": "Shop flooring", "cn": "商店地板", "cat": "floor", "color": "#aec3c5", "img": "assets/blocks/shopflooring.png"},
  {"id": "triangle_designflooring", "en": "Triangle-design flooring", "cn": "三角纹地板", "cat": "floor", "color": "#e3ba98", "img": "assets/blocks/triangle_designflooring.png"},
  {"id": "iron_plateflooring", "en": "Iron-plate flooring", "cn": "铁板地板", "cat": "floor", "color": "#787470", "img": "assets/blocks/iron_plateflooring.png"},
  {"id": "irontiling", "en": "Iron tiling", "cn": "铁瓷砖", "cat": "floor", "color": "#443a35", "img": "assets/blocks/irontiling.png"},
  {"id": "neonflooring", "en": "Neon flooring", "cn": "霓虹地板", "cat": "floor", "color": "#9c709b", "img": "assets/blocks/neonflooring.png"},
  {"id": "cyberflooring", "en": "Cyber flooring", "cn": "赛博地板", "cat": "floor", "color": "#496689", "img": "assets/blocks/cyberflooring.png"},
  {"id": "archedtiling", "en": "Arched tiling", "cn": "拱纹瓷砖", "cat": "floor", "color": "#ca716a", "img": "assets/blocks/archedtiling.png"},
  {"id": "stonetiling", "en": "Stone tiling", "cn": "石瓷砖", "cat": "floor", "color": "#9b9694", "img": "assets/blocks/stonetiling.png"},
  {"id": "squaretiling", "en": "Square tiling", "cn": "方块瓷砖", "cat": "floor", "color": "#decb98", "img": "assets/blocks/squaretiling.png"},
  {"id": "mosaictiling", "en": "Mosaic Tiling", "cn": "马赛克瓷砖", "cat": "floor", "color": "#dec474", "img": "assets/blocks/mosaictiling.png"},
  {"id": "brickflooring", "en": "Brick Flooring", "cn": "砖地板", "cat": "floor", "color": "#c27744", "img": "assets/blocks/brickflooring.png"},
  {"id": "stylishstoneflooring", "en": "Stylish Stone Flooring", "cn": "精致石地板", "cat": "floor", "color": "#8f8fa1", "img": "assets/blocks/stylishstoneflooring.png"},
  {"id": "fish_scaletiling", "en": "Fish-scale tiling", "cn": "鱼鳞瓷砖", "cat": "floor", "color": "#b9abaf", "img": "assets/blocks/fish_scaletiling.png"},
  {"id": "asphaltroad", "en": "Asphalt Road", "cn": "沥青道路", "cat": "floor", "color": "#777a86", "img": "assets/blocks/asphaltroad.png"},
  {"id": "markedroad_horizontal", "en": "Marked Road (Horizontal)", "cn": "标线道路横", "cat": "floor", "color": "#80828d", "img": "assets/blocks/markedroad_horizontal.png"},
  {"id": "markedroad_vertical", "en": "Marked Road (Vertical)", "cn": "标线道路竖", "cat": "floor", "color": "#7f818b", "img": "assets/blocks/markedroad_vertical.png"},
  {"id": "graycircleflooring", "en": "Gray circle flooring", "cn": "灰圈地板", "cat": "floor", "color": "#bfbab7", "img": "assets/blocks/graycircleflooring.png"},
  {"id": "haypile", "en": "Hay pile", "cn": "干草堆", "cat": "floor", "color": "#d3ae14", "img": "assets/blocks/haypile.png"},
  {"id": "ironplating", "en": "Iron plating", "cn": "铁铁皮", "cat": "floor", "color": "#bfb7b2", "img": "assets/blocks/ironplating.png"},
  {"id": "cubelight", "en": "Cube Light", "cn": "方块浅色", "cat": "floor", "color": "#d4d2de", "img": "assets/blocks/cubelight.png"},
  {"id": "foundation", "en": "Foundation", "cn": "地基", "cat": "floor", "color": "#b6a08d", "img": "assets/blocks/foundation.png"},
  {"id": "levee", "en": "Levee", "cn": "堤坝", "cat": "floor", "color": "#afa9ad", "img": "assets/blocks/levee.png"},
  {"id": "scrapcube", "en": "Scrap cube", "cn": "废料方块", "cat": "floor", "color": "#978b87", "img": "assets/blocks/scrapcube.png"},
  {"id": "polka_dotprint", "en": "Polka-Dot Print", "cn": "波点花纹", "cat": "print", "color": "#e77687", "img": "assets/blocks/polka_dotprint.png"},
  {"id": "vertical_stripeprint", "en": "Vertical-Stripe Print", "cn": "竖花纹", "cat": "print", "color": "#9ea2d3", "img": "assets/blocks/vertical_stripeprint.png"},
  {"id": "horizontal_stripeprint", "en": "Horizontal-Stripe Print", "cn": "横花纹", "cat": "print", "color": "#9ea2d2", "img": "assets/blocks/horizontal_stripeprint.png"},
  {"id": "ginghamprint", "en": "Gingham Print", "cn": "格纹花纹", "cat": "print", "color": "#7ccbe7", "img": "assets/blocks/ginghamprint.png"},
  {"id": "tartanprint", "en": "Tartan Print", "cn": "格子呢花纹", "cat": "print", "color": "#157671", "img": "assets/blocks/tartanprint.png"},
  {"id": "argyleprint", "en": "Argyle Print", "cn": "菱形格花纹", "cat": "print", "color": "#c95c4a", "img": "assets/blocks/argyleprint.png"},
  {"id": "berryprint", "en": "Berry Print", "cn": "树果花纹", "cat": "print", "color": "#d8d2c2", "img": "assets/blocks/berryprint.png"},
  {"id": "pokeballprint", "en": "Poke Ball Print", "cn": "精灵球花纹", "cat": "print", "color": "#d5b630", "img": "assets/blocks/pokeballprint.png"},
  {"id": "stylishpokeballprint", "en": "Stylish Poke Ball Print", "cn": "精致精灵球花纹", "cat": "print", "color": "#b25961", "img": "assets/blocks/stylishpokeballprint.png"},
  {"id": "bubbleprint", "en": "Bubble Print", "cn": "气泡花纹", "cat": "print", "color": "#d6d3ca", "img": "assets/blocks/bubbleprint.png"},
  {"id": "houndstoothprint", "en": "Houndstooth Print", "cn": "千鸟格花纹", "cat": "print", "color": "#79a6b2", "img": "assets/blocks/houndstoothprint.png"},
  {"id": "vineprint", "en": "Vine Print", "cn": "藤蔓花纹", "cat": "print", "color": "#b2c89b", "img": "assets/blocks/vineprint.png"},
  {"id": "swirlprint", "en": "Swirl Print", "cn": "漩涡花纹", "cat": "print", "color": "#e5ae9d", "img": "assets/blocks/swirlprint.png"},
  {"id": "winterprint", "en": "Winter Print", "cn": "冬季花纹", "cat": "print", "color": "#887fa6", "img": "assets/blocks/winterprint.png"},
  {"id": "zig_zagprint", "en": "Zig-zag print", "cn": "锯齿花纹", "cat": "print", "color": "#8a8b59", "img": "assets/blocks/zig_zagprint.png"},
  {"id": "leafprint", "en": "Leaf print", "cn": "叶花纹", "cat": "print", "color": "#d8d9bc", "img": "assets/blocks/leafprint.png"},
  {"id": "flowerprint", "en": "Flower print", "cn": "花花纹", "cat": "print", "color": "#e2b5c1", "img": "assets/blocks/flowerprint.png"},
  {"id": "starprint", "en": "Star print", "cn": "星花纹", "cat": "print", "color": "#cfc7b5", "img": "assets/blocks/starprint.png"},
  {"id": "curryprint", "en": "Curry print", "cn": "咖喱花纹", "cat": "print", "color": "#bab596", "img": "assets/blocks/curryprint.png"},
  {"id": "fieldgrass", "en": "Field grass", "cn": "原野草", "cat": "ground", "color": "#cdbe68", "img": "assets/blocks/fieldgrass.png"},
  {"id": "seashoregrass", "en": "Seashore grass", "cn": "海岸草", "cat": "ground", "color": "#cdc06c", "img": "assets/blocks/seashoregrass.png"},
  {"id": "alpinegrass", "en": "Alpine grass", "cn": "高山草", "cat": "ground", "color": "#767b57", "img": "assets/blocks/alpinegrass.png"},
  {"id": "sky_highgrass", "en": "Sky-high grass", "cn": "空草", "cat": "ground", "color": "#85b39d", "img": "assets/blocks/sky_highgrass.png"},
  {"id": "ordinarysoil", "en": "Ordinary soil", "cn": "普通土", "cat": "ground", "color": "#eac28b", "img": "assets/blocks/ordinarysoil.png"},
  {"id": "seashellsoil", "en": "Seashell soil", "cn": "贝壳土", "cat": "ground", "color": "#d8c689", "img": "assets/blocks/seashellsoil.png"},
  {"id": "stripedsoil", "en": "Striped soil", "cn": "条纹土", "cat": "ground", "color": "#ad815c", "img": "assets/blocks/stripedsoil.png"},
  {"id": "pure_whitesoil", "en": "Pure-white soil", "cn": "白土", "cat": "ground", "color": "#d2c8ac", "img": "assets/blocks/pure_whitesoil.png"},
  {"id": "clay", "en": "Clay", "cn": "黏土", "cat": "ground", "color": "#ceaa87", "img": "assets/blocks/clay.png"},
  {"id": "ordinarysand", "en": "Ordinary sand", "cn": "普通沙", "cat": "ground", "color": "#e9ba66", "img": "assets/blocks/ordinarysand.png"},
  {"id": "beachsand", "en": "Beach sand", "cn": "沙滩沙", "cat": "ground", "color": "#d9bf92", "img": "assets/blocks/beachsand.png"},
  {"id": "skylandsand", "en": "Skyland sand", "cn": "天空沙", "cat": "ground", "color": "#d1c297", "img": "assets/blocks/skylandsand.png"},
  {"id": "bumpybeachsand", "en": "Bumpy beach sand", "cn": "颗粒沙滩沙", "cat": "ground", "color": "#d7be92", "img": "assets/blocks/bumpybeachsand.png"},
  {"id": "volcanicash", "en": "Volcanic ash", "cn": "火山火山灰", "cat": "ground", "color": "#6d6965", "img": "assets/blocks/volcanicash.png"},
  {"id": "sandstone", "en": "Sandstone", "cn": "砂岩", "cat": "ground", "color": "#e6ad6b", "img": "assets/blocks/sandstone.png"},
  {"id": "skylandsandstone", "en": "Skyland sandstone", "cn": "天空砂岩", "cat": "ground", "color": "#cfbf9c", "img": "assets/blocks/skylandsandstone.png"},
  {"id": "cliffrock", "en": "Cliff rock", "cn": "崖壁岩石", "cat": "ground", "color": "#dfb571", "img": "assets/blocks/cliffrock.png"},
  {"id": "spottedcliffrock", "en": "Spotted cliff rock", "cn": "斑点崖壁岩石", "cat": "ground", "color": "#dfaf6d", "img": "assets/blocks/spottedcliffrock.png"},
  {"id": "redcliffrock", "en": "Red cliff rock", "cn": "红崖壁岩石", "cat": "ground", "color": "#e2a075", "img": "assets/blocks/redcliffrock.png"},
  {"id": "redspottedcliffrock", "en": "Red spotted cliff rock", "cn": "红斑点崖壁岩石", "cat": "ground", "color": "#e09973", "img": "assets/blocks/redspottedcliffrock.png"},
  {"id": "blackcliffrock", "en": "Black cliff rock", "cn": "黑崖壁岩石", "cat": "ground", "color": "#695b4e", "img": "assets/blocks/blackcliffrock.png"},
  {"id": "blackspottedcliffrock", "en": "Black spotted cliff rock", "cn": "黑斑点崖壁岩石", "cat": "ground", "color": "#5f5550", "img": "assets/blocks/blackspottedcliffrock.png"},
  {"id": "skylandcliffrock", "en": "Skyland cliff rock", "cn": "天空崖壁岩石", "cat": "ground", "color": "#d4be88", "img": "assets/blocks/skylandcliffrock.png"},
  {"id": "skylandspottedcliffrock", "en": "Skyland spotted cliff rock", "cn": "天空斑点崖壁岩石", "cat": "ground", "color": "#cebb8b", "img": "assets/blocks/skylandspottedcliffrock.png"},
  {"id": "whiterock", "en": "White rock", "cn": "白岩石", "cat": "ground", "color": "#b3acab", "img": "assets/blocks/whiterock.png"},
  {"id": "coarserock", "en": "Coarse rock", "cn": "粗糙岩石", "cat": "ground", "color": "#a4b2b1", "img": "assets/blocks/coarserock.png"},
  {"id": "lightbrownrock", "en": "Light brown rock", "cn": "浅色棕岩石", "cat": "ground", "color": "#ca855f", "img": "assets/blocks/lightbrownrock.png"},
  {"id": "redrock", "en": "Red rock", "cn": "红岩石", "cat": "ground", "color": "#916156", "img": "assets/blocks/redrock.png"},
  {"id": "yellowrock", "en": "Yellow rock", "cn": "黄岩石", "cat": "ground", "color": "#e0d247", "img": "assets/blocks/yellowrock.png"},
  {"id": "blackrock", "en": "Black rock", "cn": "黑岩石", "cat": "ground", "color": "#413129", "img": "assets/blocks/blackrock.png"},
  {"id": "lavarock", "en": "Lava rock", "cn": "熔岩岩石", "cat": "ground", "color": "#34241d", "img": "assets/blocks/lavarock.png"},
  {"id": "caverock", "en": "Cave rock", "cn": "洞穴岩石", "cat": "ground", "color": "#9193a4", "img": "assets/blocks/caverock.png"},
  {"id": "oceanrock", "en": "Ocean rock", "cn": "海岩岩石", "cat": "ground", "color": "#716568", "img": "assets/blocks/oceanrock.png"},
  {"id": "reddish_browncaverock", "en": "Reddish-brown cave rock", "cn": "红棕棕洞穴岩石", "cat": "ground", "color": "#7d5b4f", "img": "assets/blocks/reddish_browncaverock.png"},
  {"id": "volcanicrock", "en": "Volcanic rock", "cn": "火山岩石", "cat": "ground", "color": "#7b594c", "img": "assets/blocks/volcanicrock.png"},
  {"id": "carvedwhiterock", "en": "Carved white rock", "cn": "雕刻白岩石", "cat": "ground", "color": "#afadae", "img": "assets/blocks/carvedwhiterock.png"},
  {"id": "carvedcoarserock", "en": "Carved coarse rock", "cn": "雕刻粗糙岩石", "cat": "ground", "color": "#9aaaaa", "img": "assets/blocks/carvedcoarserock.png"},
  {"id": "carvedlight_brownrock", "en": "Carved light-brown rock", "cn": "雕刻浅色棕岩石", "cat": "ground", "color": "#bc8461", "img": "assets/blocks/carvedlight_brownrock.png"},
  {"id": "carvedredrock", "en": "Carved red rock", "cn": "雕刻红岩石", "cat": "ground", "color": "#85584f", "img": "assets/blocks/carvedredrock.png"},
  {"id": "carvedyellowrock", "en": "Carved yellow rock", "cn": "雕刻黄岩石", "cat": "ground", "color": "#cfc747", "img": "assets/blocks/carvedyellowrock.png"},
  {"id": "irondeposit", "en": "Iron deposit", "cn": "铁", "cat": "ground", "color": "#6b433e", "img": "assets/blocks/irondeposit.png"},
  {"id": "golddeposit", "en": "Gold deposit", "cn": "金", "cat": "ground", "color": "#5a3d33", "img": "assets/blocks/golddeposit.png"},
  {"id": "pokemetaldeposit", "en": "Pokemetal deposit", "cn": "Pokemetal deposit", "cat": "ground", "color": "#b0a790", "img": "assets/blocks/pokemetaldeposit.png"},
  {"id": "mossysoil", "en": "Mossy soil", "cn": "苔藓土", "cat": "ground", "color": "#969d2f", "img": "assets/blocks/mossysoil.png"},
  {"id": "gravel", "en": "Gravel", "cn": "砾石", "cat": "ground", "color": "#b3aba1", "img": "assets/blocks/gravel.png"},
  {"id": "limestone", "en": "Limestone", "cn": "石灰岩", "cat": "ground", "color": "#cfc49a", "img": "assets/blocks/limestone.png"},
  {"id": "glowingstone", "en": "Glowing stone", "cn": "石", "cat": "ground", "color": "#3e393f", "img": "assets/blocks/glowingstone.png"},
  {"id": "mysteriousstone", "en": "Mysterious Stone", "cn": "石", "cat": "ground", "color": "#84b3cc", "img": "assets/blocks/mysteriousstone.png"},
  {"id": "ice", "en": "Ice", "cn": "冰", "cat": "ground", "color": "#8dcfe2", "img": "assets/blocks/ice.png"},
  {"id": "crackedsandstone", "en": "Cracked sandstone", "cn": "砂岩", "cat": "ground", "color": "#d79b5f", "img": "assets/blocks/crackedsandstone.png"},
];
